# Generated by Django 3.2.12 on 2023-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='topic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
