# Generated by Django 3.2.12 on 2023-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
    ]
