# Generated by Django 3.2.12 on 2023-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
