# Generated by Django 3.2.12 on 2023-07-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20230706_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
