# Generated by Django 3.2.12 on 2023-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_customuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.TextField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.TextField(blank=True, default='', max_length=20, null=True),
        ),
    ]
